### ISSUE TITLE
Telemetry feature of onnxruntime

### ISSUE THREAD

**Issue by raphaelmenges** [supertone-inc/onnxruntime-build#1]
Hello 👋

According to the official documentation, [onnxruntime may send telemetry to Microsoft](https://github.com/microsoft/onnxruntime/blob/main/docs/Privacy.md). This feature seems to be activated by default for official Windows builds and may be activated soon for other targets as well. To my understanding, telemetry is disabled by default for custom builds of onnxruntime. How is it for the builds from this repository?

**Comment by krazijames** [comment]
https://github.com/microsoft/onnxruntime/blob/baeece44ba075009c6bfe95891a8c1b3d4571cb3/cmake/CMakeLists.txt#L124
It seems to be disabled as the default value for `onnxruntime_USE_TELEMETRY` is set to `OFF`. 😄

**Comment by raphaelmenges** [comment]
Nice! Thanks for the swift reply.
