### ISSUE TITLE
Tag v1.16.3 points to onnxruntime 1.17.0 

### ISSUE THREAD

**Issue by IvanPizhenko** [supertone-inc/onnxruntime-build#12]
Tag v1.16.3 points to onnxruntime 1.17.0. Please fix this.

**Comment by krazijames** [comment]
Currently, the tags are intended to denote which commit is used to build associated release assets and the actual ONNX Runtime version to build is set by `ONNXRUNTIME_VERSION` env variable. So the tag version and committed ONNX Runtime version may not match.
