### ISSUE TITLE
add onnxruntime-win-arm64-static_lib-1.18.1.zip

### ISSUE THREAD

**Issue by Baiyuetribe** [supertone-inc/onnxruntime-build#14]
Request to add onnxruntime-win-arm64-static_lib-1.18.1.zip

**Comment by csukuangfj** [comment]
I suggest that you have a look at https://github.com/csukuangfj/onnxruntime-libs/releases/tag/v1.18.1

![Screenshot 2024-11-15 at 14 05 19](https://github.com/user-attachments/assets/23084365-8d15-460b-8883-a442c0e68349)
