### ISSUE TITLE
Linux build (x64, WASM) of v1.19.2 fail

### ISSUE THREAD

**Issue by raphaelmenges** [supertone-inc/onnxruntime-build#15]
Hello 👋,

since the most recent version of ONNX runtime 1.19.2, the CI fails to build the Linux targets with x64 and WASM architecture. For example, the x64 build [fails as follows](https://github.com/supertone-inc/onnxruntime-build/actions/runs/10764257894/job/29846818542#step:12:485):

```
[ 19%] Building ASM object onnxruntime/CMakeFiles/onnxruntime_mlas.dir/home/runner/work/onnxruntime-build/onnxruntime-build/onnxruntime/onnxruntime/core/mlas/lib/x86_64/QgemmU8S8KernelAvx2.S.o
cc: error: unrecognized command-line option ‘-mavxvnni’; did you mean ‘-mavx512vnni’?
```

I am confused what to do about it from "our" side. It looks like a problem within ONNX runtime? Perhaps we need a different GCC version or so?

Here is I believe the bespoken command-line option that causes the problem: <https://github.com/microsoft/onnxruntime/blob/20d94648bbb106c74c43ef4023e142dee0342155/cmake/onnxruntime_mlas.cmake#L582>

PS: I found this open pull request in the Microsoft repo: <https://github.com/microsoft/onnxruntime/pull/21616>

**Comment by raphaelmenges** [comment]
I can confirm: CI works when [GCC is newer or equal 11](https://github.com/supertone-inc/onnxruntime-build/blob/efaa34b8f034fc3042138b34977146c2416eda8d/.github/workflows/build.yml#L14)!

**Comment by snnn** [comment]
WASM can support avx2? I thought it does not support any native assembly.

**Comment by raphaelmenges** [comment]
I just saw that the WASM builds fail as well. I did not check why they failed so far!

Here you go: <https://github.com/supertone-inc/onnxruntime-build/actions/runs/10764257894/job/29846819093#step:12:1250>

**Comment by krazijames** [comment]
@raphaelmenges Thank you for the report. We can successfully build v1.19.2 now!

And according to the [official documentation](https://onnxruntime.ai/docs/build/web.html#build-instructions):
> NOTE:
> - ONNX Runtime Web is dropping support for non-SIMD and non-threaded builds in future versions since v1.19.0.

So we also dropped those builds.
