### ISSUE TITLE
Request to update to onnxruntime v1.16.0

### ISSUE THREAD

**Issue by csukuangfj** [supertone-inc/onnxruntime-build#4]
https://github.com/microsoft/onnxruntime/releases/tag/v1.16.0
is out.  Could you trigger the github actions to build it?

**Comment by raphaelmenges** [comment]
Apparently, the GitHub actions are automatically executed at every onnxruntime release. However, the builds for win-x64 [fail for quite a while now](https://github.com/supertone-inc/onnxruntime-build/actions/runs/6998915322/job/19037522721#step:12:3026) with following error:

> D:\a\onnxruntime-build\onnxruntime-build\onnxruntime\onnxruntime\core\platform\windows\stacktrace.cc(13,10): fatal error C1083: Cannot open include file: 'stacktrace': No such file or directory [D:\a\onnxruntime-build\onnxruntime-build\build\static_lib\onnxruntime\onnxruntime_common.vcxproj]

**Comment by csukuangfj** [comment]
> Apparently, the GitHub actions are automatically executed at every onnxruntime release. However, the builds for win-x64 [fail for quite a while now](https://github.com/supertone-inc/onnxruntime-build/actions/runs/6998915322/job/19037522721#step:12:3026) with following error:
> 
> > D:\a\onnxruntime-build\onnxruntime-build\onnxruntime\onnxruntime\core\platform\windows\stacktrace.cc(13,10): fatal error C1083: Cannot open include file: 'stacktrace': No such file or directory [D:\a\onnxruntime-build\onnxruntime-build\build\static_lib\onnxruntime\onnxruntime_common.vcxproj]

It has been fixed in my fork.

**Comment by raphaelmenges** [comment]
Will you make a pull request into this repo?
